### ISSUE TITLE
I experience a panic problem

### ISSUE THREAD

**Issue by hawkhsieh** [rockneurotiko/go-tgbot#4]
The crash report is here:

Received message: {"message_id":1588,"from":{"id":167535807,"first_name":"gggg","last_name":"hhhhh"},"date":1459216957,"chat":{"id":-112010465,"title":"Software-軟體開發"},"new_chat_title":"Software-軟體開發"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x4065bc]

goroutine 26 [running]:
panic(0x9d12c0, 0xc82000a0e0)
    /usr/local/go/src/runtime/panic.go:464 +0x3e6
main.allMsgHand(0xb4e2e0, 0x2d, 0xc82042e290, 0xa, 0xb5bdf1f, 0xc82042e2b0, 0xa, 0xc82005ebe0, 0x4c, 0xc820058ae0, ...)
    /home/spotcam/go/src/spotcambot/main.go:359 +0x1bc
github.com/rockneurotiko/go-tgbot.CustomCall.call(0xbbab10, 0xbbac20, 0xb4e2e0, 0x2d, 0xc82042e290, 0xa, 0xb5bdf1f, 0xc82042e2b0, 0xa, 0xc82005ebe0, ...)
    /home/spotcam/go/src/github.com/rockneurotiko/go-tgbot/callbacktypes.go:27 +0x52
github.com/rockneurotiko/go-tgbot.(*CustomCall).call(0xc82042e2c0, 0xb4e2e0, 0x2d, 0xc82042e290, 0xa, 0xb5bdf1f, 0xc82042e2b0, 0xa, 0xc82005ebe0, 0x4c, ...)
    <autogenerated>:108 +0xd5
github.com/rockneurotiko/go-tgbot.TgBot.ProcessAllMsg(0xb4e2e0, 0x2d, 0xc82042e290, 0xa, 0xb5bdf1f, 0xc82042e2b0, 0xa, 0xc82005ebe0, 0x4c, 0xc820058ae0, ...)
    /home/spotcam/go/src/github.com/rockneurotiko/go-tgbot/tgbot.go:116 +0x31f
created by github.com/rockneurotiko/go-tgbot.TgBot.MessagesHandler
    /home/spotcam/go/src/github.com/rockneurotiko/go-tgbot/tgbot.go:132 +0xbf

**Comment by rockneurotiko** [comment]
Can you paste the code or some little snippet that do it?

**Comment by hawkhsieh** [comment]
My tgbot was crashing when I modified the title from Software to Software-軟體開發. Maybe the uni-code is the root cause.

**Comment by rockneurotiko** [comment]
I don't know, I've never have any problem with unicode, but if you can paste some code to reproduce this I can see what is going on.

**Comment by rockneurotiko** [comment]
What was the problem? Just to know if I have to fix something.

**Comment by hawkhsieh** [comment]
Eventually, I find the problem is mine.
Thank you very much.
